name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clean install
        run: rm -rf node_modules package-lock.json && npm install

      - name: Generate Static Site
        run: npm run generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: your-custom-domain.com # (Optional, remove if not using a custom domain)
